/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/angiology 2.glb -o src/components/AngiologyModel.tsx 
Author: Z-Anatomy (https://sketchfab.com/Z-Anatomy)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/angiology-0caae8f894cc40b69f3f78adf14b9665
Title: Angiology
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_149: THREE.Mesh
    Object_151: THREE.Mesh
    Object_153: THREE.Mesh
  }
  materials: {
    Artery: THREE.MeshStandardMaterial
    Cartilage: THREE.MeshStandardMaterial
    Ligament: THREE.MeshStandardMaterial
    Muscles: THREE.MeshStandardMaterial
    Vein: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Model(props: any) {
  const { nodes, materials } = useGLTF('/angiology.glb') as any
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Artery} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.Cartilage} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.Artery} />
      <mesh geometry={nodes.Object_149.geometry} material={materials.Ligament} />
      <mesh geometry={nodes.Object_151.geometry} material={materials.Muscles} />
      <mesh geometry={nodes.Object_153.geometry} material={materials.Vein} />
    </group>
  )
}

useGLTF.preload('/angiology.glb')
