/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/ecorche_-_anatomy_study.glb -o src/components/EcorcheModel.tsx 
Author: Beatriz Gomez Santamaria (https://sketchfab.com/BeatrizGomez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ecorche-anatomy-study-e402d3d541eb4b199c57d5410f5d3c57
Title: Ecorche - Anatomy study
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_9: THREE.Mesh
    Object_11: THREE.Mesh
  }
  materials: {
    material_0: THREE.MeshStandardMaterial
    material_1: THREE.MeshStandardMaterial
    material_2: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function EcorcheModel({ opacity = 1, depthWrite = true, color = '#ffffff', roughness = 1, ...props }: any) {
  const { nodes, materials } = useGLTF('/ecorche_-_anatomy_study.glb') as any
  
  React.useEffect(() => {
    (Object.values(materials) as any[]).forEach((mat) => {
      mat.transparent = opacity < 1;
      mat.opacity = opacity;
      mat.depthWrite = depthWrite;
      mat.color = new THREE.Color(color);
      mat.roughness = roughness;
      mat.needsUpdate = true;
    });
  }, [materials, opacity, depthWrite, color, roughness]);

  return (
    <group {...props} dispose={null}>
      <group scale={1}>
        <group position={[-13.012, -5.517, -44.057]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.material_0} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.material_0} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.material_0} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.material_0} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.material_1} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.material_2} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ecorche_-_anatomy_study.glb')
